# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alestockUI_v2.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1319, 702)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(16, 426, 1314, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.grain_recipe = QtGui.QTableWidget(self.centralwidget)
        self.grain_recipe.setGeometry(QtCore.QRect(418, 453, 223, 81))
        self.grain_recipe.setMinimumSize(QtCore.QSize(223, 0))
        self.grain_recipe.setMaximumSize(QtCore.QSize(250, 16777215))
        self.grain_recipe.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.grain_recipe.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.grain_recipe.setRowCount(6)
        self.grain_recipe.setColumnCount(2)
        self.grain_recipe.setObjectName(_fromUtf8("grain_recipe"))
        item = QtGui.QTableWidgetItem()
        self.grain_recipe.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.grain_recipe.setHorizontalHeaderItem(1, item)
        self.grain_recipe.horizontalHeader().setVisible(True)
        self.grain_recipe.horizontalHeader().setDefaultSectionSize(101)
        self.grain_recipe.verticalHeader().setVisible(False)
        self.grain_recipe.verticalHeader().setDefaultSectionSize(15)
        self.hop_recipe = QtGui.QTableWidget(self.centralwidget)
        self.hop_recipe.setGeometry(QtCore.QRect(650, 453, 324, 81))
        self.hop_recipe.setMinimumSize(QtCore.QSize(324, 0))
        self.hop_recipe.setMaximumSize(QtCore.QSize(324, 16777215))
        self.hop_recipe.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.hop_recipe.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.hop_recipe.setRowCount(6)
        self.hop_recipe.setColumnCount(3)
        self.hop_recipe.setObjectName(_fromUtf8("hop_recipe"))
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(2, item)
        self.hop_recipe.horizontalHeader().setVisible(True)
        self.hop_recipe.horizontalHeader().setDefaultSectionSize(101)
        self.hop_recipe.verticalHeader().setVisible(False)
        self.hop_recipe.verticalHeader().setDefaultSectionSize(15)
        self.recipe_results = QtGui.QTableWidget(self.centralwidget)
        self.recipe_results.setGeometry(QtCore.QRect(417, 544, 101, 104))
        self.recipe_results.setMinimumSize(QtCore.QSize(0, 38))
        self.recipe_results.setMaximumSize(QtCore.QSize(176, 16777215))
        self.recipe_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recipe_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recipe_results.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.recipe_results.setRowCount(4)
        self.recipe_results.setColumnCount(1)
        self.recipe_results.setObjectName(_fromUtf8("recipe_results"))
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setHorizontalHeaderItem(0, item)
        self.recipe_results.horizontalHeader().setVisible(False)
        self.recipe_results.horizontalHeader().setDefaultSectionSize(90)
        self.recipe_results.verticalHeader().setVisible(True)
        self.recipe_results.verticalHeader().setDefaultSectionSize(25)
        self.recipe_results.verticalHeader().setMinimumSectionSize(25)
        self.label_process = QtGui.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(556, 649, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_process.setFont(font)
        self.label_process.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process.setObjectName(_fromUtf8("label_process"))
        self.processNotes = QtGui.QTextEdit(self.centralwidget)
        self.processNotes.setGeometry(QtCore.QRect(556, 545, 196, 100))
        self.processNotes.setMinimumSize(QtCore.QSize(0, 100))
        self.processNotes.setObjectName(_fromUtf8("processNotes"))
        self.tastingNotes = QtGui.QTextEdit(self.centralwidget)
        self.tastingNotes.setGeometry(QtCore.QRect(780, 545, 196, 100))
        self.tastingNotes.setMinimumSize(QtCore.QSize(0, 100))
        self.tastingNotes.setObjectName(_fromUtf8("tastingNotes"))
        self.label_tastingNotes = QtGui.QLabel(self.centralwidget)
        self.label_tastingNotes.setGeometry(QtCore.QRect(780, 649, 75, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_tastingNotes.setFont(font)
        self.label_tastingNotes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tastingNotes.setObjectName(_fromUtf8("label_tastingNotes"))
        self.search_results = QtGui.QListWidget(self.centralwidget)
        self.search_results.setGeometry(QtCore.QRect(281, 452, 121, 204))
        self.search_results.setMinimumSize(QtCore.QSize(121, 0))
        self.search_results.setMaximumSize(QtCore.QSize(121, 16777215))
        self.search_results.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.search_results.setObjectName(_fromUtf8("search_results"))
        self.calendar = QtGui.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(20, 453, 256, 129))
        self.calendar.setGridVisible(True)
        self.calendar.setVerticalHeaderFormat(QtGui.QCalendarWidget.ISOWeekNumbers)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(True)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.search_box = QtGui.QTextEdit(self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(20, 586, 256, 41))
        self.search_box.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.search_box.setFont(font)
        self.search_box.setObjectName(_fromUtf8("search_box"))
        self.label_rateSearch = QtGui.QLabel(self.centralwidget)
        self.label_rateSearch.setGeometry(QtCore.QRect(21, 633, 96, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rateSearch.setFont(font)
        self.label_rateSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rateSearch.setObjectName(_fromUtf8("label_rateSearch"))
        self.button_search = QtGui.QPushButton(self.centralwidget)
        self.button_search.setGeometry(QtCore.QRect(210, 633, 64, 21))
        self.button_search.setObjectName(_fromUtf8("button_search"))
        self.rating_input = QtGui.QSpinBox(self.centralwidget)
        self.rating_input.setGeometry(QtCore.QRect(115, 632, 39, 22))
        self.rating_input.setObjectName(_fromUtf8("rating_input"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(11, -5, 1299, 16))
        self.line_8.setLineWidth(10)
        self.line_8.setMidLineWidth(5)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.yeast_stock = QtGui.QTableWidget(self.centralwidget)
        self.yeast_stock.setGeometry(QtCore.QRect(1100, 14, 201, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeast_stock.sizePolicy().hasHeightForWidth())
        self.yeast_stock.setSizePolicy(sizePolicy)
        self.yeast_stock.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yeast_stock.setFont(font)
        self.yeast_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.yeast_stock.setAlternatingRowColors(True)
        self.yeast_stock.setRowCount(12)
        self.yeast_stock.setColumnCount(2)
        self.yeast_stock.setObjectName(_fromUtf8("yeast_stock"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.yeast_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.yeast_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.yeast_stock.setItem(0, 0, item)
        self.yeast_stock.horizontalHeader().setCascadingSectionResizes(False)
        self.yeast_stock.horizontalHeader().setDefaultSectionSize(97)
        self.yeast_stock.horizontalHeader().setSortIndicatorShown(False)
        self.yeast_stock.horizontalHeader().setStretchLastSection(True)
        self.yeast_stock.verticalHeader().setVisible(False)
        self.yeast_stock.verticalHeader().setDefaultSectionSize(31)
        self.yeast_stock.verticalHeader().setStretchLastSection(True)
        self.hop_stock = QtGui.QTableWidget(self.centralwidget)
        self.hop_stock.setGeometry(QtCore.QRect(560, 15, 527, 211))
        self.hop_stock.setMaximumSize(QtCore.QSize(527, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hop_stock.setFont(font)
        self.hop_stock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hop_stock.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hop_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.hop_stock.setAlternatingRowColors(True)
        self.hop_stock.setRowCount(12)
        self.hop_stock.setObjectName(_fromUtf8("hop_stock"))
        self.hop_stock.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hop_stock.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setItem(0, 2, item)
        self.hop_stock.horizontalHeader().setVisible(True)
        self.hop_stock.horizontalHeader().setDefaultSectionSize(171)
        self.hop_stock.horizontalHeader().setStretchLastSection(True)
        self.hop_stock.verticalHeader().setVisible(False)
        self.hop_stock.verticalHeader().setDefaultSectionSize(31)
        self.grain_stock = QtGui.QTableWidget(self.centralwidget)
        self.grain_stock.setGeometry(QtCore.QRect(15, 15, 528, 211))
        self.grain_stock.setMaximumSize(QtCore.QSize(528, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.grain_stock.setFont(font)
        self.grain_stock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grain_stock.setAutoFillBackground(False)
        self.grain_stock.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.grain_stock.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.grain_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.grain_stock.setAlternatingRowColors(True)
        self.grain_stock.setRowCount(12)
        self.grain_stock.setObjectName(_fromUtf8("grain_stock"))
        self.grain_stock.setColumnCount(4)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.grain_stock.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 3, item)
        self.grain_stock.horizontalHeader().setVisible(True)
        self.grain_stock.horizontalHeader().setCascadingSectionResizes(True)
        self.grain_stock.horizontalHeader().setDefaultSectionSize(130)
        self.grain_stock.horizontalHeader().setSortIndicatorShown(False)
        self.grain_stock.horizontalHeader().setStretchLastSection(True)
        self.grain_stock.verticalHeader().setVisible(False)
        self.grain_stock.verticalHeader().setCascadingSectionResizes(True)
        self.grain_stock.verticalHeader().setDefaultSectionSize(31)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(982, 250, 321, 176))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_params = QtGui.QWidget()
        self.tab_params.setObjectName(_fromUtf8("tab_params"))
        self.button_commit = QtGui.QPushButton(self.tab_params)
        self.button_commit.setGeometry(QtCore.QRect(205, 115, 70, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 118, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_commit.setPalette(palette)
        self.button_commit.setObjectName(_fromUtf8("button_commit"))
        self.brew_params = QtGui.QTableWidget(self.tab_params)
        self.brew_params.setGeometry(QtCore.QRect(12, 0, 271, 48))
        self.brew_params.setMinimumSize(QtCore.QSize(0, 48))
        self.brew_params.setMaximumSize(QtCore.QSize(296, 51))
        self.brew_params.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_params.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_params.setObjectName(_fromUtf8("brew_params"))
        self.brew_params.setColumnCount(3)
        self.brew_params.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.brew_params.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.brew_params.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.brew_params.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.brew_params.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 2, item)
        self.brew_params.horizontalHeader().setDefaultSectionSize(90)
        self.brew_params.horizontalHeader().setHighlightSections(True)
        self.brew_params.horizontalHeader().setMinimumSectionSize(20)
        self.brew_params.verticalHeader().setVisible(False)
        self.brew_params.verticalHeader().setDefaultSectionSize(25)
        self.brew_params.verticalHeader().setHighlightSections(True)
        self.brew_results = QtGui.QTableWidget(self.tab_params)
        self.brew_results.setGeometry(QtCore.QRect(12, 50, 271, 48))
        self.brew_results.setMinimumSize(QtCore.QSize(0, 48))
        self.brew_results.setMaximumSize(QtCore.QSize(296, 51))
        self.brew_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_results.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.brew_results.setObjectName(_fromUtf8("brew_results"))
        self.brew_results.setColumnCount(3)
        self.brew_results.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.brew_results.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.brew_results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.brew_results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.brew_results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 2, item)
        self.brew_results.horizontalHeader().setDefaultSectionSize(90)
        self.brew_results.horizontalHeader().setHighlightSections(True)
        self.brew_results.horizontalHeader().setMinimumSectionSize(20)
        self.brew_results.verticalHeader().setVisible(False)
        self.brew_results.verticalHeader().setDefaultSectionSize(25)
        self.brew_results.verticalHeader().setHighlightSections(True)
        self.yeast_use = QtGui.QTableWidget(self.tab_params)
        self.yeast_use.setGeometry(QtCore.QRect(12, 100, 185, 48))
        self.yeast_use.setMinimumSize(QtCore.QSize(1, 48))
        self.yeast_use.setMaximumSize(QtCore.QSize(201, 51))
        self.yeast_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.yeast_use.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.yeast_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.yeast_use.setObjectName(_fromUtf8("yeast_use"))
        self.yeast_use.setColumnCount(2)
        self.yeast_use.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.yeast_use.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.yeast_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.yeast_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.yeast_use.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.yeast_use.setItem(0, 1, item)
        self.yeast_use.horizontalHeader().setDefaultSectionSize(90)
        self.yeast_use.horizontalHeader().setHighlightSections(True)
        self.yeast_use.horizontalHeader().setMinimumSectionSize(20)
        self.yeast_use.verticalHeader().setVisible(False)
        self.yeast_use.verticalHeader().setDefaultSectionSize(25)
        self.yeast_use.verticalHeader().setHighlightSections(True)
        self.tabWidget.addTab(self.tab_params, _fromUtf8(""))
        self.tab_timer = QtGui.QWidget()
        self.tab_timer.setObjectName(_fromUtf8("tab_timer"))
        self.layoutWidget = QtGui.QWidget(self.tab_timer)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 40, 158, 83))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.time_input = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.time_input.setFont(font)
        self.time_input.setMaximum(999)
        self.time_input.setObjectName(_fromUtf8("time_input"))
        self.gridLayout_2.addWidget(self.time_input, 0, 0, 1, 1)
        self.rem_time = QtGui.QPlainTextEdit(self.layoutWidget)
        self.rem_time.setMinimumSize(QtCore.QSize(80, 0))
        self.rem_time.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.rem_time.setFont(font)
        self.rem_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rem_time.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rem_time.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rem_time.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rem_time.setBackgroundVisible(False)
        self.rem_time.setCenterOnScroll(True)
        self.rem_time.setObjectName(_fromUtf8("rem_time"))
        self.gridLayout_2.addWidget(self.rem_time, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 1, 1, 1)
        self.button_startTimer = QtGui.QPushButton(self.layoutWidget)
        self.button_startTimer.setMaximumSize(QtCore.QSize(80, 40))
        self.button_startTimer.setObjectName(_fromUtf8("button_startTimer"))
        self.gridLayout_2.addWidget(self.button_startTimer, 2, 0, 1, 1)
        self.button_stopTimer = QtGui.QPushButton(self.layoutWidget)
        self.button_stopTimer.setMaximumSize(QtCore.QSize(80, 40))
        self.button_stopTimer.setObjectName(_fromUtf8("button_stopTimer"))
        self.gridLayout_2.addWidget(self.button_stopTimer, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_timer, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.button_reStock = QtGui.QRadioButton(self.tab)
        self.button_reStock.setGeometry(QtCore.QRect(26, 85, 74, 21))
        self.button_reStock.setObjectName(_fromUtf8("button_reStock"))
        self.button_use = QtGui.QRadioButton(self.tab)
        self.button_use.setGeometry(QtCore.QRect(26, 115, 46, 21))
        self.button_use.setObjectName(_fromUtf8("button_use"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(25, 15, 246, 61))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.grain_use = QtGui.QTableWidget(self.centralwidget)
        self.grain_use.setGeometry(QtCore.QRect(10, 250, 478, 146))
        self.grain_use.setMinimumSize(QtCore.QSize(478, 0))
        self.grain_use.setMaximumSize(QtCore.QSize(478, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grain_use.setFont(font)
        self.grain_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.grain_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.grain_use.setAlternatingRowColors(True)
        self.grain_use.setRowCount(8)
        self.grain_use.setColumnCount(3)
        self.grain_use.setObjectName(_fromUtf8("grain_use"))
        item = QtGui.QTableWidgetItem()
        self.grain_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.grain_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.grain_use.setHorizontalHeaderItem(2, item)
        self.grain_use.horizontalHeader().setVisible(True)
        self.grain_use.horizontalHeader().setDefaultSectionSize(171)
        self.grain_use.horizontalHeader().setStretchLastSection(True)
        self.grain_use.verticalHeader().setVisible(False)
        self.grain_use.verticalHeader().setHighlightSections(True)
        self.grain_use.verticalHeader().setStretchLastSection(True)
        self.hop_use = QtGui.QTableWidget(self.centralwidget)
        self.hop_use.setGeometry(QtCore.QRect(495, 250, 478, 146))
        self.hop_use.setMinimumSize(QtCore.QSize(478, 0))
        self.hop_use.setMaximumSize(QtCore.QSize(478, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hop_use.setFont(font)
        self.hop_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hop_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.hop_use.setAlternatingRowColors(True)
        self.hop_use.setRowCount(8)
        self.hop_use.setColumnCount(3)
        self.hop_use.setObjectName(_fromUtf8("hop_use"))
        item = QtGui.QTableWidgetItem()
        self.hop_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hop_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hop_use.setHorizontalHeaderItem(2, item)
        self.hop_use.horizontalHeader().setVisible(True)
        self.hop_use.horizontalHeader().setDefaultSectionSize(171)
        self.hop_use.horizontalHeader().setStretchLastSection(True)
        self.hop_use.verticalHeader().setVisible(False)
        self.hop_use.verticalHeader().setHighlightSections(True)
        self.hop_use.verticalHeader().setStretchLastSection(True)
        self.label_name = QtGui.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(1115, 452, 59, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.label_age = QtGui.QLabel(self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(1060, 495, 169, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_age.setFont(font)
        self.label_age.setAlignment(QtCore.Qt.AlignCenter)
        self.label_age.setObjectName(_fromUtf8("label_age"))
        self.button_noteSave = QtGui.QPushButton(self.centralwidget)
        self.button_noteSave.setGeometry(QtCore.QRect(1105, 620, 87, 21))
        self.button_noteSave.setObjectName(_fromUtf8("button_noteSave"))
        self.checkBox_active = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_active.setGeometry(QtCore.QRect(1115, 525, 59, 21))
        self.checkBox_active.setObjectName(_fromUtf8("checkBox_active"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1090, 590, 120, 18))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_rating = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rating.setFont(font)
        self.label_rating.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rating.setObjectName(_fromUtf8("label_rating"))
        self.horizontalLayout.addWidget(self.label_rating)
        self.rating = KRatingWidget(self.layoutWidget1)
        self.rating.setObjectName(_fromUtf8("rating"))
        self.horizontalLayout.addWidget(self.rating)
        self.box_style = QtGui.QComboBox(self.centralwidget)
        self.box_style.setGeometry(QtCore.QRect(1090, 555, 121, 22))
        self.box_style.setIconSize(QtCore.QSize(20, 16))
        self.box_style.setObjectName(_fromUtf8("box_style"))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1025, 440, 236, 211))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.button_grainUseUpdate = QtGui.QPushButton(self.centralwidget)
        self.button_grainUseUpdate.setGeometry(QtCore.QRect(20, 405, 81, 21))
        self.button_grainUseUpdate.setObjectName(_fromUtf8("button_grainUseUpdate"))
        self.button_hopUseUpdate = QtGui.QPushButton(self.centralwidget)
        self.button_hopUseUpdate.setGeometry(QtCore.QRect(510, 405, 81, 21))
        self.button_hopUseUpdate.setObjectName(_fromUtf8("button_hopUseUpdate"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(5, 230, 1311, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.Load_data = QtGui.QAction(MainWindow)
        self.Load_data.setObjectName(_fromUtf8("Load_data"))
        self.Save_Data = QtGui.QAction(MainWindow)
        self.Save_Data.setObjectName(_fromUtf8("Save_Data"))
        self.Load_Brew = QtGui.QAction(MainWindow)
        self.Load_Brew.setObjectName(_fromUtf8("Load_Brew"))
        self.Save_Brew = QtGui.QAction(MainWindow)
        self.Save_Brew.setObjectName(_fromUtf8("Save_Brew"))
        self.Save_Brew_As = QtGui.QAction(MainWindow)
        self.Save_Brew_As.setObjectName(_fromUtf8("Save_Brew_As"))
        self.menuFile.addAction(self.Load_data)
        self.menuFile.addAction(self.Save_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Load_Brew)
        self.menuFile.addAction(self.Save_Brew)
        self.menuFile.addAction(self.Save_Brew_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.grain_recipe.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Grain", None))
        item = self.grain_recipe.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kg.", None))
        item = self.hop_recipe.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_recipe.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Grams", None))
        item = self.hop_recipe.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.recipe_results.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        item = self.recipe_results.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.recipe_results.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "OG", None))
        item = self.recipe_results.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.recipe_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        self.label_process.setText(_translate("MainWindow", "Process Notes", None))
        self.label_tastingNotes.setText(_translate("MainWindow", "Tasting Notes", None))
        self.label_rateSearch.setText(_translate("MainWindow", "Filter By Rating", None))
        self.button_search.setText(_translate("MainWindow", "Search", None))
        item = self.yeast_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.yeast_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pkts", None))
        __sortingEnabled = self.yeast_stock.isSortingEnabled()
        self.yeast_stock.setSortingEnabled(False)
        self.yeast_stock.setSortingEnabled(__sortingEnabled)
        item = self.hop_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Alpha", None))
        item = self.hop_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Grams", None))
        __sortingEnabled = self.hop_stock.isSortingEnabled()
        self.hop_stock.setSortingEnabled(False)
        self.hop_stock.setSortingEnabled(__sortingEnabled)
        item = self.grain_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "    Grain    ", None))
        item = self.grain_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.grain_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Extract L/Kg.", None))
        item = self.grain_stock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kg.", None))
        __sortingEnabled = self.grain_stock.isSortingEnabled()
        self.grain_stock.setSortingEnabled(False)
        self.grain_stock.setSortingEnabled(__sortingEnabled)
        self.button_commit.setText(_translate("MainWindow", "Commit", None))
        item = self.brew_params.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mash Temp", None))
        item = self.brew_params.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mash Eff", None))
        item = self.brew_params.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Volume", None))
        __sortingEnabled = self.brew_params.isSortingEnabled()
        self.brew_params.setSortingEnabled(False)
        self.brew_params.setSortingEnabled(__sortingEnabled)
        item = self.brew_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        item = self.brew_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.brew_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "OG", None))
        __sortingEnabled = self.brew_results.isSortingEnabled()
        self.brew_results.setSortingEnabled(False)
        self.brew_results.setSortingEnabled(__sortingEnabled)
        item = self.yeast_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.yeast_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pkts", None))
        __sortingEnabled = self.yeast_use.isSortingEnabled()
        self.yeast_use.setSortingEnabled(False)
        self.yeast_use.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_params), _translate("MainWindow", "Parameters", None))
        self.label_9.setText(_translate("MainWindow", "Set Timer", None))
        self.label_17.setText(_translate("MainWindow", " Mins To Go", None))
        self.button_startTimer.setText(_translate("MainWindow", "Start", None))
        self.button_stopTimer.setText(_translate("MainWindow", "Stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_timer), _translate("MainWindow", "Timer", None))
        self.button_reStock.setText(_translate("MainWindow", "Re-Stock", None))
        self.button_use.setText(_translate("MainWindow", "Use", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Select Re-Stock to change contents of stock tables. </p><p>Select Use for recipe formulation.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mode", None))
        item = self.grain_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Grain", None))
        item = self.grain_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kg.", None))
        item = self.grain_use.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "%", None))
        item = self.hop_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Grams", None))
        item = self.hop_use.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        self.label_name.setText(_translate("MainWindow", "Name", None))
        self.label_age.setText(_translate("MainWindow", "<html><head/><body><p>21 days since brewed</p></body></html>", None))
        self.button_noteSave.setText(_translate("MainWindow", "Save Notes", None))
        self.checkBox_active.setText(_translate("MainWindow", "Active", None))
        self.label_rating.setText(_translate("MainWindow", "Rating", None))
        self.box_style.setItemText(0, _translate("MainWindow", "Style", None))
        self.box_style.setItemText(1, _translate("MainWindow", "Summer Ale", None))
        self.box_style.setItemText(2, _translate("MainWindow", "American IPA", None))
        self.box_style.setItemText(3, _translate("MainWindow", "IPA", None))
        self.box_style.setItemText(4, _translate("MainWindow", "English Pale Ale", None))
        self.box_style.setItemText(5, _translate("MainWindow", "Stout", None))
        self.box_style.setItemText(6, _translate("MainWindow", "Porter", None))
        self.button_grainUseUpdate.setText(_translate("MainWindow", "Update ", None))
        self.button_hopUseUpdate.setText(_translate("MainWindow", "Update ", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.Load_data.setText(_translate("MainWindow", "Load data", None))
        self.Save_Data.setText(_translate("MainWindow", "Save Data", None))
        self.Load_Brew.setText(_translate("MainWindow", "Load Brew", None))
        self.Save_Brew.setText(_translate("MainWindow", "Save Brew", None))
        self.Save_Brew_As.setText(_translate("MainWindow", "Save Brew As", None))

from PyKDE4.kdeui import KRatingWidget
