# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alestockUI_v2.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1319, 702)
        font = QtGui.QFont()
        
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(16, 426, 1314, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.recipe_results = QtGui.QTableWidget(self.centralwidget)
        self.recipe_results.setGeometry(QtCore.QRect(462, 544, 101, 104))
        self.recipe_results.setMinimumSize(QtCore.QSize(0, 38))
        self.recipe_results.setMaximumSize(QtCore.QSize(176, 16777215))
        self.recipe_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recipe_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recipe_results.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.recipe_results.setRowCount(5)
        self.recipe_results.setColumnCount(1)
        self.recipe_results.setObjectName(_fromUtf8("recipe_results"))
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.recipe_results.setHorizontalHeaderItem(0, item)
        self.recipe_results.horizontalHeader().setVisible(False)
        self.recipe_results.horizontalHeader().setDefaultSectionSize(90)
        self.recipe_results.verticalHeader().setVisible(True)
        self.recipe_results.verticalHeader().setDefaultSectionSize(20)
        self.recipe_results.verticalHeader().setMinimumSectionSize(25)
        self.label_process = QtGui.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(606, 645, 81, 16))
        font = QtGui.QFont()
        
        font.setWeight(50)
        self.label_process.setFont(font)
        self.label_process.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process.setObjectName(_fromUtf8("label_process"))
        self.label_tastingNotes = QtGui.QLabel(self.centralwidget)
        self.label_tastingNotes.setGeometry(QtCore.QRect(830, 645, 75, 16))
        font = QtGui.QFont()
        
        font.setWeight(50)
        self.label_tastingNotes.setFont(font)
        self.label_tastingNotes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tastingNotes.setObjectName(_fromUtf8("label_tastingNotes"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(11, -5, 1299, 16))
        self.line_8.setLineWidth(10)
        self.line_8.setMidLineWidth(5)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.yeast_stock = QtGui.QTableWidget(self.centralwidget)
        self.yeast_stock.setGeometry(QtCore.QRect(1100, 15, 201, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeast_stock.sizePolicy().hasHeightForWidth())
        self.yeast_stock.setSizePolicy(sizePolicy)
        self.yeast_stock.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yeast_stock.setFont(font)
        self.yeast_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.yeast_stock.setAlternatingRowColors(True)
        self.yeast_stock.setRowCount(12)
        self.yeast_stock.setColumnCount(2)
        self.yeast_stock.setObjectName(_fromUtf8("yeast_stock"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.yeast_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.yeast_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.yeast_stock.setItem(0, 0, item)
        self.yeast_stock.horizontalHeader().setCascadingSectionResizes(False)
        self.yeast_stock.horizontalHeader().setDefaultSectionSize(97)
        self.yeast_stock.horizontalHeader().setSortIndicatorShown(False)
        self.yeast_stock.horizontalHeader().setStretchLastSection(True)
        self.yeast_stock.verticalHeader().setVisible(False)
        self.yeast_stock.verticalHeader().setDefaultSectionSize(31)
        self.yeast_stock.verticalHeader().setStretchLastSection(True)
        self.hop_stock = QtGui.QTableWidget(self.centralwidget)
        self.hop_stock.setGeometry(QtCore.QRect(560, 15, 527, 211))
        self.hop_stock.setMaximumSize(QtCore.QSize(527, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hop_stock.setFont(font)
        self.hop_stock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hop_stock.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hop_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.hop_stock.setAlternatingRowColors(True)
        self.hop_stock.setRowCount(24)
        self.hop_stock.setObjectName(_fromUtf8("hop_stock"))
        self.hop_stock.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hop_stock.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_stock.setItem(0, 2, item)
        self.hop_stock.horizontalHeader().setVisible(True)
        self.hop_stock.horizontalHeader().setDefaultSectionSize(171)
        self.hop_stock.horizontalHeader().setStretchLastSection(True)
        self.hop_stock.verticalHeader().setVisible(False)
        self.hop_stock.verticalHeader().setDefaultSectionSize(31)
        self.grain_stock = QtGui.QTableWidget(self.centralwidget)
        self.grain_stock.setGeometry(QtCore.QRect(15, 15, 528, 211))
        self.grain_stock.setMaximumSize(QtCore.QSize(528, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.grain_stock.setFont(font)
        self.grain_stock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grain_stock.setAutoFillBackground(False)
        self.grain_stock.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.grain_stock.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.grain_stock.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.grain_stock.setAlternatingRowColors(True)
        self.grain_stock.setRowCount(24)
        self.grain_stock.setObjectName(_fromUtf8("grain_stock"))
        self.grain_stock.setColumnCount(4)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_stock.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.grain_stock.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grain_stock.setItem(0, 3, item)
        self.grain_stock.horizontalHeader().setVisible(True)
        self.grain_stock.horizontalHeader().setCascadingSectionResizes(True)
        self.grain_stock.horizontalHeader().setDefaultSectionSize(130)
        self.grain_stock.horizontalHeader().setSortIndicatorShown(False)
        self.grain_stock.horizontalHeader().setStretchLastSection(True)
        self.grain_stock.verticalHeader().setVisible(False)
        self.grain_stock.verticalHeader().setCascadingSectionResizes(True)
        self.grain_stock.verticalHeader().setDefaultSectionSize(31)
        self.grain_use = QtGui.QTableWidget(self.centralwidget)
        self.grain_use.setGeometry(QtCore.QRect(15, 250, 385, 171))
        self.grain_use.setMinimumSize(QtCore.QSize(0, 0))
        self.grain_use.setMaximumSize(QtCore.QSize(478, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grain_use.setFont(font)
        self.grain_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.grain_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.grain_use.setAlternatingRowColors(True)
        self.grain_use.setRowCount(8)
        self.grain_use.setColumnCount(3)
        self.grain_use.setObjectName(_fromUtf8("grain_use"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.grain_use.setHorizontalHeaderItem(2, item)
        self.grain_use.horizontalHeader().setVisible(True)
        self.grain_use.horizontalHeader().setDefaultSectionSize(120)
        self.grain_use.horizontalHeader().setStretchLastSection(True)
        self.grain_use.verticalHeader().setVisible(False)
        self.grain_use.verticalHeader().setHighlightSections(True)
        self.grain_use.verticalHeader().setStretchLastSection(True)
        self.hop_use = QtGui.QTableWidget(self.centralwidget)
        self.hop_use.setGeometry(QtCore.QRect(410, 250, 385, 171))
        self.hop_use.setMinimumSize(QtCore.QSize(0, 0))
        self.hop_use.setMaximumSize(QtCore.QSize(478, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hop_use.setFont(font)
        self.hop_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hop_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.hop_use.setAlternatingRowColors(True)
        self.hop_use.setRowCount(8)
        self.hop_use.setColumnCount(3)
        self.hop_use.setObjectName(_fromUtf8("hop_use"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_use.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.hop_use.setItem(0, 0, item)
        self.hop_use.horizontalHeader().setVisible(True)
        self.hop_use.horizontalHeader().setDefaultSectionSize(120)
        self.hop_use.horizontalHeader().setStretchLastSection(True)
        self.hop_use.verticalHeader().setVisible(False)
        self.hop_use.verticalHeader().setHighlightSections(True)
        self.hop_use.verticalHeader().setStretchLastSection(True)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(450, 440, 846, 226))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_rating = QtGui.QLabel(self.frame)
        self.label_rating.setGeometry(QtCore.QRect(735, 153, 34, 16))
        font = QtGui.QFont()
        
        font.setWeight(50)
        self.label_rating.setFont(font)
        self.label_rating.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rating.setObjectName(_fromUtf8("label_rating"))
        self.rating = QtGui.QSpinBox(self.frame)
        self.rating.setGeometry(QtCore.QRect(775, 150, 48, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rating.setFont(font)
        self.rating.setMaximum(10)
        self.rating.setObjectName(_fromUtf8("rating"))
        self.box_style = QtGui.QComboBox(self.frame)
        self.box_style.setGeometry(QtCore.QRect(595, 150, 101, 22))
        self.box_style.setIconSize(QtCore.QSize(20, 16))
        self.box_style.setObjectName(_fromUtf8("box_style"))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.box_style.addItem(_fromUtf8(""))
        self.processNotes = QtGui.QTextEdit(self.frame)
        self.processNotes.setGeometry(QtCore.QRect(150, 105, 196, 100))
        self.processNotes.setMinimumSize(QtCore.QSize(0, 100))
        self.processNotes.setObjectName(_fromUtf8("processNotes"))
        self.tastingNotes = QtGui.QTextEdit(self.frame)
        self.tastingNotes.setGeometry(QtCore.QRect(375, 105, 196, 100))
        self.tastingNotes.setMinimumSize(QtCore.QSize(0, 100))
        self.tastingNotes.setObjectName(_fromUtf8("tastingNotes"))
        self.button_useRecipe = QtGui.QPushButton(self.frame)
        self.button_useRecipe.setGeometry(QtCore.QRect(595, 173, 81, 21))
        self.button_useRecipe.setObjectName(_fromUtf8("button_useRecipe"))
        self.label_name = QtGui.QLabel(self.frame)
        self.label_name.setGeometry(QtCore.QRect(715, 187, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(725, 182, 101, 33))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.button_saveNotes = QtGui.QPushButton(self.frame)
        self.button_saveNotes.setGeometry(QtCore.QRect(595, 195, 81, 21))
        self.button_saveNotes.setObjectName(_fromUtf8("button_saveNotes"))
        self.button_saveBrew = QtGui.QPushButton(self.centralwidget)
        self.button_saveBrew.setGeometry(QtCore.QRect(999, 280, 81, 21))
        self.button_saveBrew.setObjectName(_fromUtf8("button_saveBrew"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(5, 230, 1311, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.yeast_use = QtGui.QTableWidget(self.centralwidget)
        self.yeast_use.setGeometry(QtCore.QRect(810, 250, 181, 51))
        self.yeast_use.setMinimumSize(QtCore.QSize(1, 48))
        self.yeast_use.setMaximumSize(QtCore.QSize(201, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yeast_use.setFont(font)
        self.yeast_use.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.yeast_use.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.yeast_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.yeast_use.setObjectName(_fromUtf8("yeast_use"))
        self.yeast_use.setColumnCount(2)
        self.yeast_use.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.yeast_use.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.yeast_use.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.yeast_use.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.yeast_use.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.yeast_use.setItem(0, 1, item)
        self.yeast_use.horizontalHeader().setDefaultSectionSize(90)
        self.yeast_use.horizontalHeader().setHighlightSections(True)
        self.yeast_use.horizontalHeader().setMinimumSectionSize(33)
        self.yeast_use.verticalHeader().setVisible(False)
        self.yeast_use.verticalHeader().setDefaultSectionSize(30)
        self.yeast_use.verticalHeader().setHighlightSections(True)
        self.yeast_use.verticalHeader().setMinimumSectionSize(20)
        self.time_input = QtGui.QSpinBox(self.centralwidget)
        self.time_input.setGeometry(QtCore.QRect(1119, 250, 72, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        
        font.setWeight(50)
        self.time_input.setFont(font)
        self.time_input.setMaximum(999)
        self.time_input.setObjectName(_fromUtf8("time_input"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1119, 290, 72, 12))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.button_stopTimer = QtGui.QPushButton(self.centralwidget)
        self.button_stopTimer.setGeometry(QtCore.QRect(1200, 310, 72, 21))
        self.button_stopTimer.setMaximumSize(QtCore.QSize(80, 40))
        self.button_stopTimer.setObjectName(_fromUtf8("button_stopTimer"))
        self.rem_time = QtGui.QPlainTextEdit(self.centralwidget)
        self.rem_time.setGeometry(QtCore.QRect(1200, 250, 72, 40))
        self.rem_time.setMinimumSize(QtCore.QSize(72, 0))
        self.rem_time.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        
        font.setWeight(50)
        self.rem_time.setFont(font)
        self.rem_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rem_time.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rem_time.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rem_time.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.rem_time.setBackgroundVisible(False)
        self.rem_time.setCenterOnScroll(True)
        self.rem_time.setObjectName(_fromUtf8("rem_time"))
        self.button_startTimer = QtGui.QPushButton(self.centralwidget)
        self.button_startTimer.setGeometry(QtCore.QRect(1119, 310, 72, 21))
        self.button_startTimer.setMaximumSize(QtCore.QSize(80, 40))
        self.button_startTimer.setObjectName(_fromUtf8("button_startTimer"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1195, 290, 80, 12))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 440, 411, 226))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.file_search = QtGui.QTabWidget(self.frame_3)
        self.file_search.setGeometry(QtCore.QRect(15, 16, 246, 198))
        self.file_search.setTabPosition(QtGui.QTabWidget.South)
        self.file_search.setObjectName(_fromUtf8("file_search"))
        self.tab_file = QtGui.QWidget()
        self.tab_file.setObjectName(_fromUtf8("tab_file"))
        self.file_list = QtGui.QListWidget(self.tab_file)
        self.file_list.setGeometry(QtCore.QRect(10, 10, 216, 146))
        self.file_list.setObjectName(_fromUtf8("file_list"))
        self.file_search.addTab(self.tab_file, _fromUtf8(""))
        self.tab_search = QtGui.QWidget()
        self.tab_search.setObjectName(_fromUtf8("tab_search"))
        self.ratingPlusMinus = QtGui.QSpinBox(self.tab_search)
        self.ratingPlusMinus.setGeometry(QtCore.QRect(169, 115, 44, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ratingPlusMinus.setFont(font)
        self.ratingPlusMinus.setObjectName(_fromUtf8("ratingPlusMinus"))
        self.rating_input = QtGui.QSpinBox(self.tab_search)
        self.rating_input.setGeometry(QtCore.QRect(105, 115, 44, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rating_input.setFont(font)
        self.rating_input.setObjectName(_fromUtf8("rating_input"))
        self.label_rateSearch = QtGui.QLabel(self.tab_search)
        self.label_rateSearch.setGeometry(QtCore.QRect(20, 115, 81, 25))
        font = QtGui.QFont()
        
        font.setWeight(50)
        self.label_rateSearch.setFont(font)
        self.label_rateSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rateSearch.setObjectName(_fromUtf8("label_rateSearch"))
        self.label_plusMinus = QtGui.QLabel(self.tab_search)
        self.label_plusMinus.setGeometry(QtCore.QRect(159, 115, 16, 16))
        self.label_plusMinus.setObjectName(_fromUtf8("label_plusMinus"))
        self.search_box = QtGui.QTextEdit(self.tab_search)
        self.search_box.setGeometry(QtCore.QRect(6, 16, 224, 96))
        self.search_box.setObjectName(_fromUtf8("search_box"))
        self.widget = QtGui.QWidget(self.tab_search)
        self.widget.setGeometry(QtCore.QRect(145, 141, 8, 25))
        self.widget.setMaximumSize(QtCore.QSize(8, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.button_search = QtGui.QPushButton(self.tab_search)
        self.button_search.setGeometry(QtCore.QRect(151, 145, 61, 21))
        self.button_search.setObjectName(_fromUtf8("button_search"))
        self.file_search.addTab(self.tab_search, _fromUtf8(""))
        self.search_results = QtGui.QListWidget(self.frame_3)
        self.search_results.setGeometry(QtCore.QRect(266, 16, 134, 179))
        self.search_results.setObjectName(_fromUtf8("search_results"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(1143, 350, 106, 31))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_brewName = QtGui.QLabel(self.frame_5)
        self.label_brewName.setGeometry(QtCore.QRect(10, 9, 85, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_brewName.setFont(font)
        self.label_brewName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_brewName.setObjectName(_fromUtf8("label_brewName"))
        self.button_writeNotes = QtGui.QPushButton(self.centralwidget)
        self.button_writeNotes.setGeometry(QtCore.QRect(999, 250, 82, 21))
        self.button_writeNotes.setObjectName(_fromUtf8("button_writeNotes"))
        self.brew_results = QtGui.QTableWidget(self.centralwidget)
        self.brew_results.setGeometry(QtCore.QRect(810, 370, 271, 48))
        self.brew_results.setMinimumSize(QtCore.QSize(0, 48))
        self.brew_results.setMaximumSize(QtCore.QSize(296, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.brew_results.setFont(font)
        self.brew_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_results.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.brew_results.setObjectName(_fromUtf8("brew_results"))
        self.brew_results.setColumnCount(3)
        self.brew_results.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.brew_results.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_results.setItem(0, 2, item)
        self.brew_results.horizontalHeader().setDefaultSectionSize(90)
        self.brew_results.horizontalHeader().setHighlightSections(True)
        self.brew_results.horizontalHeader().setMinimumSectionSize(20)
        self.brew_results.verticalHeader().setVisible(False)
        self.brew_results.verticalHeader().setDefaultSectionSize(25)
        self.brew_results.verticalHeader().setHighlightSections(True)
        self.brew_params = QtGui.QTableWidget(self.centralwidget)
        self.brew_params.setGeometry(QtCore.QRect(810, 310, 271, 48))
        self.brew_params.setMinimumSize(QtCore.QSize(0, 48))
        self.brew_params.setMaximumSize(QtCore.QSize(296, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.brew_params.setFont(font)
        self.brew_params.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_params.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brew_params.setObjectName(_fromUtf8("brew_params"))
        self.brew_params.setColumnCount(3)
        self.brew_params.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.brew_params.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_params.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_params.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        
        font.setWeight(50)
        item.setFont(font)
        self.brew_params.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.brew_params.setItem(0, 2, item)
        self.brew_params.horizontalHeader().setDefaultSectionSize(90)
        self.brew_params.horizontalHeader().setHighlightSections(True)
        self.brew_params.horizontalHeader().setMinimumSectionSize(20)
        self.brew_params.verticalHeader().setVisible(False)
        self.brew_params.verticalHeader().setDefaultSectionSize(25)
        self.brew_params.verticalHeader().setHighlightSections(True)
        self.button_commit = QtGui.QPushButton(self.centralwidget)
        self.button_commit.setGeometry(QtCore.QRect(1161, 390, 70, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 118, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_commit.setPalette(palette)
        self.button_commit.setObjectName(_fromUtf8("button_commit"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hop_recipe = QtGui.QTableWidget(self.centralwidget)
        self.hop_recipe.setGeometry(QtCore.QRect(750, 455, 285, 81))
        self.hop_recipe.setMinimumSize(QtCore.QSize(0, 0))
        self.hop_recipe.setMaximumSize(QtCore.QSize(324, 16777215))
        self.hop_recipe.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hop_recipe.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.hop_recipe.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.hop_recipe.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.hop_recipe.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.hop_recipe.setRowCount(6)
        self.hop_recipe.setColumnCount(3)
        self.hop_recipe.setObjectName(_fromUtf8("hop_recipe"))
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hop_recipe.setHorizontalHeaderItem(2, item)
        self.hop_recipe.horizontalHeader().setVisible(True)
        self.hop_recipe.horizontalHeader().setDefaultSectionSize(88)
        self.hop_recipe.verticalHeader().setVisible(False)
        self.hop_recipe.verticalHeader().setDefaultSectionSize(15)
        self.grain_recipe = QtGui.QTableWidget(self.centralwidget)
        self.grain_recipe.setGeometry(QtCore.QRect(460, 455, 285, 81))
        self.grain_recipe.setMinimumSize(QtCore.QSize(223, 0))
        self.grain_recipe.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.grain_recipe.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.grain_recipe.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.grain_recipe.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.grain_recipe.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.grain_recipe.setRowCount(6)
        self.grain_recipe.setColumnCount(3)
        self.grain_recipe.setObjectName(_fromUtf8("grain_recipe"))
        item = QtGui.QTableWidgetItem()
        self.grain_recipe.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.grain_recipe.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.grain_recipe.setHorizontalHeaderItem(2, item)
        self.grain_recipe.horizontalHeader().setVisible(True)
        self.grain_recipe.horizontalHeader().setDefaultSectionSize(88)
        self.grain_recipe.verticalHeader().setVisible(False)
        self.grain_recipe.verticalHeader().setDefaultSectionSize(15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.Load_data = QtGui.QAction(MainWindow)
        self.Load_data.setObjectName(_fromUtf8("Load_data"))
        self.Save_Data = QtGui.QAction(MainWindow)
        self.Save_Data.setObjectName(_fromUtf8("Save_Data"))
        self.Load_Brew = QtGui.QAction(MainWindow)
        self.Load_Brew.setObjectName(_fromUtf8("Load_Brew"))
        self.Save_Brew = QtGui.QAction(MainWindow)
        self.Save_Brew.setObjectName(_fromUtf8("Save_Brew"))
        self.Save_Brew_As = QtGui.QAction(MainWindow)
        self.Save_Brew_As.setObjectName(_fromUtf8("Save_Brew_As"))
        self.button_prefs = QtGui.QAction(MainWindow)
        self.button_prefs.setObjectName(_fromUtf8("button_prefs"))
        self.button_hydrCorr = QtGui.QAction(MainWindow)
        self.button_hydrCorr.setObjectName(_fromUtf8("button_hydrCorr"))
        self.menuFile.addAction(self.Load_data)
        self.menuFile.addAction(self.Save_Data)
        self.menuFile.addSeparator()
        self.menuPreferences.addAction(self.button_prefs)
        self.menuPreferences.addAction(self.button_hydrCorr)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(MainWindow)
        self.file_search.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.grain_recipe.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Grain", None))
        item = self.grain_recipe.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kg.", None))
        item = self.grain_recipe.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "%", None))
        item = self.recipe_results.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        item = self.recipe_results.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.recipe_results.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "OG", None))
        item = self.recipe_results.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temp", None))
        item = self.recipe_results.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.recipe_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        self.label_process.setText(_translate("MainWindow", "Process Notes", None))
        self.label_tastingNotes.setText(_translate("MainWindow", "Tasting Notes", None))
        item = self.yeast_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.yeast_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pkts", None))
        __sortingEnabled = self.yeast_stock.isSortingEnabled()
        self.yeast_stock.setSortingEnabled(False)
        self.yeast_stock.setSortingEnabled(__sortingEnabled)
        item = self.hop_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Alpha", None))
        item = self.hop_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Grams", None))
        __sortingEnabled = self.hop_stock.isSortingEnabled()
        self.hop_stock.setSortingEnabled(False)
        self.hop_stock.setSortingEnabled(__sortingEnabled)
        item = self.grain_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "    Grain    ", None))
        item = self.grain_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.grain_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Extract L/Kg.", None))
        item = self.grain_stock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kg.", None))
        __sortingEnabled = self.grain_stock.isSortingEnabled()
        self.grain_stock.setSortingEnabled(False)
        self.grain_stock.setSortingEnabled(__sortingEnabled)
        item = self.grain_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Grain", None))
        item = self.grain_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kg.", None))
        item = self.grain_use.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "%", None))
        item = self.hop_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Grams", None))
        item = self.hop_use.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        __sortingEnabled = self.hop_use.isSortingEnabled()
        self.hop_use.setSortingEnabled(False)
        self.hop_use.setSortingEnabled(__sortingEnabled)
        self.label_rating.setText(_translate("MainWindow", "Rating", None))
        self.box_style.setItemText(0, _translate("MainWindow", "Style", None))
        self.box_style.setItemText(1, _translate("MainWindow", "Summer Ale", None))
        self.box_style.setItemText(2, _translate("MainWindow", "American IPA", None))
        self.box_style.setItemText(3, _translate("MainWindow", "IPA", None))
        self.box_style.setItemText(4, _translate("MainWindow", "English Pale Ale", None))
        self.box_style.setItemText(5, _translate("MainWindow", "Stout", None))
        self.box_style.setItemText(6, _translate("MainWindow", "Porter", None))
        self.button_useRecipe.setText(_translate("MainWindow", "Use Recipe", None))
        self.label_name.setText(_translate("MainWindow", "Name", None))
        self.button_saveNotes.setText(_translate("MainWindow", "Save notes", None))
        self.button_saveBrew.setText(_translate("MainWindow", "Save Brew", None))
        item = self.yeast_use.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yeast", None))
        item = self.yeast_use.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pkts", None))
        __sortingEnabled = self.yeast_use.isSortingEnabled()
        self.yeast_use.setSortingEnabled(False)
        self.yeast_use.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "Set Timer", None))
        self.button_stopTimer.setText(_translate("MainWindow", "Stop", None))
        self.button_startTimer.setText(_translate("MainWindow", "Start", None))
        self.label_17.setText(_translate("MainWindow", " Mins To Go", None))
        self.file_search.setTabText(self.file_search.indexOf(self.tab_file), _translate("MainWindow", "File", None))
        self.label_rateSearch.setText(_translate("MainWindow", "Filter By Rating", None))
        self.label_plusMinus.setText(_translate("MainWindow", "+", None))
        self.button_search.setText(_translate("MainWindow", "Search", None))
        self.file_search.setTabText(self.file_search.indexOf(self.tab_search), _translate("MainWindow", "Search", None))
        self.label_brewName.setText(_translate("MainWindow", "TextLabel", None))
        self.button_writeNotes.setText(_translate("MainWindow", "Write Notes", None))
        item = self.brew_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EBU", None))
        item = self.brew_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EBC", None))
        item = self.brew_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "OG", None))
        __sortingEnabled = self.brew_results.isSortingEnabled()
        self.brew_results.setSortingEnabled(False)
        self.brew_results.setSortingEnabled(__sortingEnabled)
        item = self.brew_params.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mash Temp", None))
        item = self.brew_params.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mash Eff", None))
        item = self.brew_params.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Volume", None))
        __sortingEnabled = self.brew_params.isSortingEnabled()
        self.brew_params.setSortingEnabled(False)
        self.brew_params.setSortingEnabled(__sortingEnabled)
        self.button_commit.setText(_translate("MainWindow", "Commit", None))
        item = self.hop_recipe.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hop", None))
        item = self.hop_recipe.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Grams", None))
        item = self.hop_recipe.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Tools", None))
        self.Load_data.setText(_translate("MainWindow", "Load Data", None))
        self.Save_Data.setText(_translate("MainWindow", "Save Data", None))
        self.Load_Brew.setText(_translate("MainWindow", "Load Brew", None))
        self.Save_Brew.setText(_translate("MainWindow", "Save Brew", None))
        self.Save_Brew_As.setText(_translate("MainWindow", "Save Brew As", None))
        self.button_prefs.setText(_translate("MainWindow", "Preferences", None))
        self.button_hydrCorr.setText(_translate("MainWindow", "Hydrometer Correction", None))

